### ISSUE TITLE
Allow load dynamic onnx lib

### ISSUE THREAD

**Issue by hlhr202** [nkeenan38/voice_activity_detector#26]
Could you bypass a feature flag to ort "load-dynamic" feature? This may solve some linking issues when building ort with other libraries (eg. whisper-rs) that may conflict with this library under windows MSVC.

https://docs.rs/ort/latest/ort/#how-to-get-binaries

**Comment by nkeenan38** [comment]
Hey. Just added the `load-dynamic` feature flag to the library, which just enables the same feature in the `ort` crate. You can reference that library's documentation for setting the library path.
